version: "3.9" #compose版本，一般是3.x

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_USER: douyin
      MYSQL_PASSWORD: douyin
      MYSQL_DATABASE: douyin
      MYSQL_ROOT_PASSWORD: douyin
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  redis:
    image: redis:5.0.13
    volumes:
      - ./redis/:/data
    environment:
      - TZ=Asia/Shanghai
    
  api:
    image: "${IMAGE_URI}"
    ports: #将容器端口暴露
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai #设置容器时间为北京时间
      PORT: 8080
      DB_SOURCE: douyin:douyin@tcp(mysql:3306)/douyin?charset=utf8mb4&parseTime=True&loc=Local
    depends_on: #依赖容器，必须先运行前置依赖容器
      - mysql
      - redis
    volumes:
      - ./logs/douyin.log:/app/logs/douyin.log
    entrypoint: ["/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh"]
    command: ["./main"]
