version: "3.9" #compose版本，一般是3.x

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_USER: douyin
      MYSQL_PASSWORD: douyin
      MYSQL_DATABASE: douyin
      MYSQL_ROOT_PASSWORD: douyin
    ports:
      - 3306:3306

  api:
    image: "${IMAGE_URI}"
    ports: #将容器端口暴露
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai #设置容器时间为北京时间
      PORT: 8080
      DB_SOURCE: douyin:douyin@tcp(mysql:3306)/douyin?charset=utf8mb4&parseTime=True&loc=Local
    depends_on: #依赖容器，必须先运行前置依赖容器
      - mysql
    volumes:
      - ./douyin.log:/app/douyin.log
    entrypoint: ["/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh"]
    command: ["./main"]
