name: Deployment

on:
  workflow_run:
    workflows: ["image-build-push"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: deploy image
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export REGISTRY="registry.cn-hangzhou.aliyuncs.com"
            export IMAGE_URI="${REGISTRY}/whyy1/douyin:${{ github.sha }}"
            echo $IMAGE_URI
            docker login -u=${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_TOKEN }}  $REGISTRY
            echo 'y' | docker system prune $1
            docker pull $IMAGE_URI
            cd douyin
            curl https://ghproxy.com/https://raw.githubusercontent.com/whyy1/douyin/main/docker-compose.yml > docker-compose.yml
            echo "test----> "
            ls
            pwd
            docker-compose up -d
