name: image-build-push

on:
  push:
    branches:
      - "main"
      - "beta"
      - "alpha"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/whyy1/douyin:${{ github.sha }}
